# LachShield config
# We use MiniMessages and the color format.
# Learn more about the syntax here: https://docs.advntr.dev/minimessage/format.html

# General plugin messages.
messages:
  noPermission: "<red>You don't have permission to execute this command!"
  reloadSuccess: "<green>The LachShield configuration has been successfully reloaded."

# Limit connections that come from the same IP address.
IPLimiter:
  enabled: true
  maxAccountsPerIp: 3
  kickMessage: "<red>You have reached the account limit on the server!"

# Prevent players to access the nether roof.
AntiNetherRoof:
  enabled: false
  warnMessage: "<red>You cannot enter the Nether roof!"

# Kick AFK players after some minutes
AntiAFK:
  enabled: false
  timeoutMinutes: 15
  kickMessage: "<red>You have been disconnected for AFK."

# Hide player data that can bee seen through hacks or mods.
HidePlayerData:
  enabled: false
  toObfuscate:
    health: true
    stackSize: true
    durability: true
    difficulty: true
    onGround: true

# Players can't throw ender pearls in blocks to "phase" into them.
AntiPearlPhase:
  enabled: false

# Filter certain words/elements out in chat.
ChatFilter:
  enabled: false
  warning:
    enabled: true
    message: "<red>Hey watch your words!"
  blacklist: # Insert blacklisted words here.
    - "test"
    - "test1"