# LachShield config
# We use MiniMessages and the color format.
# Learn more about the syntax here: https://docs.advntr.dev/minimessage/format.html

# Ip limit
ip_limit:
  enabled: true
  maxAccountsPerIp: 3
  kickMessage: "<red>>You have reached the account limit on the server!"

# PreventNetherRoof
prevent_nether_roof:
  enabled: false
  warningMessage: "<red>You cannot enter the Nether roof!"

# Broadcast messages
broadcast:
  prefix: "<dark_aqua>[<red>Broadcast<dark_aqua>]" # remove the text for no prefix
  messageColor: "<gold>"

# Kick AFK players after some minutes
afk:
  enabled: false
  afkTimeoutMinutes: 15
  kickMessage: "<red>You have been disconnected for AFK."

# Avoids other players to see some player data through hacks.
obfuscate-player-data:
  enabled: false
  toObfuscate:
    health: true
    ping: true
    stackSize: true
    durability: true
    difficulty: true
    onGround: true