# LachShield config
# We use minimessages and the colourformat.
# Learn more here: https://docs.advntr.dev/minimessage/format.html
ip_limit:
  enabled: true
  max_accounts_per_ip: 3
  kick_message: "<red>>You have reached the account limit on the server!"

# PreventNetherRoof
prevent_nether_roof:
  enabled: false
  warning_message: "<red>You cannot enter the Nether roof!"