name: LachShield
version: ${version}
main: de.lachcrafter.lachshield.LachShield
api-version: '1.21'
folia-supported: true
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true