name: LachShield
version: '${version}'
main: de.lachcrafter.lachshield.LachShield
api-version: '1.21'
folia-supported: true
commands:
  lachshield:
    iplimit:
      usage: /LachShield iplimit <max ips>
      description: Sets the limit of the ips that can join at the same time.